package client.entity;
// Generated May 14, 2013 3:06:40 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private int id;
     private String usename;
     private String password;

    public Admin() {
    }

    public Admin(int id, String usename, String password) {
       this.id = id;
       this.usename = usename;
       this.password = password;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsename() {
        return this.usename;
    }
    
    public void setUsename(String usename) {
        this.usename = usename;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


