package client.entity;
// Generated May 14, 2013 3:06:40 PM by Hibernate Tools 3.2.1.GA



/**
 * CvLocation generated by hbm2java
 */
public class CvLocation  implements java.io.Serializable {


     private int id;
     private Cv cv;
     private Location location;

    public CvLocation() {
    }

	
    public CvLocation(int id) {
        this.id = id;
    }
    public CvLocation(int id, Cv cv, Location location) {
       this.id = id;
       this.cv = cv;
       this.location = location;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cv getCv() {
        return this.cv;
    }
    
    public void setCv(Cv cv) {
        this.cv = cv;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }




}


