package client.entity;
// Generated May 14, 2013 3:06:40 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * LevelJob generated by hbm2java
 */
public class LevelJob  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<Cv> cvs = new HashSet<Cv>(0);
     private Set<Recruitment> recruitments = new HashSet<Recruitment>(0);

    public LevelJob() {
    }

	
    public LevelJob(int id) {
        this.id = id;
    }
    public LevelJob(int id, String name, Set<Cv> cvs, Set<Recruitment> recruitments) {
       this.id = id;
       this.name = name;
       this.cvs = cvs;
       this.recruitments = recruitments;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Cv> getCvs() {
        return this.cvs;
    }
    
    public void setCvs(Set<Cv> cvs) {
        this.cvs = cvs;
    }
    public Set<Recruitment> getRecruitments() {
        return this.recruitments;
    }
    
    public void setRecruitments(Set<Recruitment> recruitments) {
        this.recruitments = recruitments;
    }




}


