package client.entity;
// Generated May 14, 2013 3:06:40 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private int id;
     private String useName;
     private String password;
     private Boolean role;
     private Set<Worker> workers = new HashSet<Worker>(0);
     private Set<Customer> customers = new HashSet<Customer>(0);

    public Account() {
    }

	
    public Account(int id, String useName, String password) {
        this.id = id;
        this.useName = useName;
        this.password = password;
    }
    public Account(int id, String useName, String password, Boolean role, Set<Worker> workers, Set<Customer> customers) {
       this.id = id;
       this.useName = useName;
       this.password = password;
       this.role = role;
       this.workers = workers;
       this.customers = customers;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUseName() {
        return this.useName;
    }
    
    public void setUseName(String useName) {
        this.useName = useName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getRole() {
        return this.role;
    }
    
    public void setRole(Boolean role) {
        this.role = role;
    }
    public Set<Worker> getWorkers() {
        return this.workers;
    }
    
    public void setWorkers(Set<Worker> workers) {
        this.workers = workers;
    }
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }




}


