package client.entity;
// Generated May 14, 2013 3:06:40 PM by Hibernate Tools 3.2.1.GA



/**
 * CvCategory generated by hbm2java
 */
public class CvCategory  implements java.io.Serializable {


     private int id;
     private Cv cv;
     private Category category;

    public CvCategory() {
    }

	
    public CvCategory(int id) {
        this.id = id;
    }
    public CvCategory(int id, Cv cv, Category category) {
       this.id = id;
       this.cv = cv;
       this.category = category;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cv getCv() {
        return this.cv;
    }
    
    public void setCv(Cv cv) {
        this.cv = cv;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }




}


