package client.entity;
// Generated May 14, 2013 3:06:40 PM by Hibernate Tools 3.2.1.GA



/**
 * RecruitmentCategory generated by hbm2java
 */
public class RecruitmentCategory  implements java.io.Serializable {


     private int id;
     private Recruitment recruitment;
     private Category category;

    public RecruitmentCategory() {
    }

	
    public RecruitmentCategory(int id) {
        this.id = id;
    }
    public RecruitmentCategory(int id, Recruitment recruitment, Category category) {
       this.id = id;
       this.recruitment = recruitment;
       this.category = category;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Recruitment getRecruitment() {
        return this.recruitment;
    }
    
    public void setRecruitment(Recruitment recruitment) {
        this.recruitment = recruitment;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }




}


