package client.entity;
// Generated May 14, 2013 3:06:40 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;

/**
 * Appointment generated by hbm2java
 */
public class Appointment  implements java.io.Serializable {


     private int id;
     private Customer customer;
     private Worker worker;
     private Date dateTime;
     private String info;

    public Appointment() {
    }

	
    public Appointment(int id) {
        this.id = id;
    }
    public Appointment(int id, Customer customer, Worker worker, Date dateTime, String info) {
       this.id = id;
       this.customer = customer;
       this.worker = worker;
       this.dateTime = dateTime;
       this.info = info;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Worker getWorker() {
        return this.worker;
    }
    
    public void setWorker(Worker worker) {
        this.worker = worker;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }




}


