package client.entity;
// Generated May 14, 2013 3:06:40 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<RecruitmentLocation> recruitmentLocations = new HashSet<RecruitmentLocation>(0);
     private Set<CvLocation> cvLocations = new HashSet<CvLocation>(0);

    public Location() {
    }

	
    public Location(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Location(int id, String name, Set<RecruitmentLocation> recruitmentLocations, Set<CvLocation> cvLocations) {
       this.id = id;
       this.name = name;
       this.recruitmentLocations = recruitmentLocations;
       this.cvLocations = cvLocations;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<RecruitmentLocation> getRecruitmentLocations() {
        return this.recruitmentLocations;
    }
    
    public void setRecruitmentLocations(Set<RecruitmentLocation> recruitmentLocations) {
        this.recruitmentLocations = recruitmentLocations;
    }
    public Set<CvLocation> getCvLocations() {
        return this.cvLocations;
    }
    
    public void setCvLocations(Set<CvLocation> cvLocations) {
        this.cvLocations = cvLocations;
    }




}


