package client.entity;
// Generated May 14, 2013 3:06:40 PM by Hibernate Tools 3.2.1.GA



/**
 * RecruitmentToWorker generated by hbm2java
 */
public class RecruitmentToWorker  implements java.io.Serializable {


     private int id;
     private Worker worker;
     private Recruitment recruitment;

    public RecruitmentToWorker() {
    }

	
    public RecruitmentToWorker(int id) {
        this.id = id;
    }
    public RecruitmentToWorker(int id, Worker worker, Recruitment recruitment) {
       this.id = id;
       this.worker = worker;
       this.recruitment = recruitment;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Worker getWorker() {
        return this.worker;
    }
    
    public void setWorker(Worker worker) {
        this.worker = worker;
    }
    public Recruitment getRecruitment() {
        return this.recruitment;
    }
    
    public void setRecruitment(Recruitment recruitment) {
        this.recruitment = recruitment;
    }




}


