package client.entity;
// Generated May 14, 2013 3:06:40 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private int id;
     private String categoryName;
     private Set<RecruitmentCategory> recruitmentCategories = new HashSet<RecruitmentCategory>(0);
     private Set<CvCategory> cvCategories = new HashSet<CvCategory>(0);

    public Category() {
    }

	
    public Category(int id, String categoryName) {
        this.id = id;
        this.categoryName = categoryName;
    }
    public Category(int id, String categoryName, Set<RecruitmentCategory> recruitmentCategories, Set<CvCategory> cvCategories) {
       this.id = id;
       this.categoryName = categoryName;
       this.recruitmentCategories = recruitmentCategories;
       this.cvCategories = cvCategories;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Set<RecruitmentCategory> getRecruitmentCategories() {
        return this.recruitmentCategories;
    }
    
    public void setRecruitmentCategories(Set<RecruitmentCategory> recruitmentCategories) {
        this.recruitmentCategories = recruitmentCategories;
    }
    public Set<CvCategory> getCvCategories() {
        return this.cvCategories;
    }
    
    public void setCvCategories(Set<CvCategory> cvCategories) {
        this.cvCategories = cvCategories;
    }




}


