package client.entity;
// Generated May 14, 2013 3:06:40 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private int id;
     private Account account;
     private String name;
     private String address;
     private String phone;
     private String logo;
     private String description;
     private Set<Appointment> appointments = new HashSet<Appointment>(0);
     private Set<FeedbackCustomer> feedbackCustomers = new HashSet<FeedbackCustomer>(0);
     private Set<Recruitment> recruitments = new HashSet<Recruitment>(0);
     private Set<FeedbackSystem> feedbackSystems = new HashSet<FeedbackSystem>(0);

    public Customer() {
    }

	
    public Customer(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Customer(int id, Account account, String name, String address, String phone, String logo, String description, Set<Appointment> appointments, Set<FeedbackCustomer> feedbackCustomers, Set<Recruitment> recruitments, Set<FeedbackSystem> feedbackSystems) {
       this.id = id;
       this.account = account;
       this.name = name;
       this.address = address;
       this.phone = phone;
       this.logo = logo;
       this.description = description;
       this.appointments = appointments;
       this.feedbackCustomers = feedbackCustomers;
       this.recruitments = recruitments;
       this.feedbackSystems = feedbackSystems;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<Appointment> getAppointments() {
        return this.appointments;
    }
    
    public void setAppointments(Set<Appointment> appointments) {
        this.appointments = appointments;
    }
    public Set<FeedbackCustomer> getFeedbackCustomers() {
        return this.feedbackCustomers;
    }
    
    public void setFeedbackCustomers(Set<FeedbackCustomer> feedbackCustomers) {
        this.feedbackCustomers = feedbackCustomers;
    }
    public Set<Recruitment> getRecruitments() {
        return this.recruitments;
    }
    
    public void setRecruitments(Set<Recruitment> recruitments) {
        this.recruitments = recruitments;
    }
    public Set<FeedbackSystem> getFeedbackSystems() {
        return this.feedbackSystems;
    }
    
    public void setFeedbackSystems(Set<FeedbackSystem> feedbackSystems) {
        this.feedbackSystems = feedbackSystems;
    }




}


