package client.entity;
// Generated May 14, 2013 3:06:40 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

/**
 * Education generated by hbm2java
 */
public class Education  implements java.io.Serializable {


     private int id;
     private Cv cv;
     private String nameSchool;
     private String degeeLevel;
     private String fildOfStudy;
     private String fromDate;
     private String toDate;
     private String achiement;

    public Education() {
    }

	
    public Education(int id) {
        this.id = id;
    }
    public Education(int id, Cv cv, String nameSchool, String degeeLevel, String fildOfStudy, String fromDate, String toDate, String achiement) {
       this.id = id;
       this.cv = cv;
       this.nameSchool = nameSchool;
       this.degeeLevel = degeeLevel;
       this.fildOfStudy = fildOfStudy;
       this.fromDate = fromDate;
       this.toDate = toDate;
       this.achiement = achiement;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cv getCv() {
        return this.cv;
    }
    
    public void setCv(Cv cv) {
        this.cv = cv;
    }
    public String getNameSchool() {
        return this.nameSchool;
    }
    
    public void setNameSchool(String nameSchool) {
        this.nameSchool = nameSchool;
    }
    public String getDegeeLevel() {
        return this.degeeLevel;
    }
    
    public void setDegeeLevel(String degeeLevel) {
        this.degeeLevel = degeeLevel;
    }
    public String getFildOfStudy() {
        return this.fildOfStudy;
    }
    
    public void setFildOfStudy(String fildOfStudy) {
        this.fildOfStudy = fildOfStudy;
    }
    public String getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(String fromDate) {
        this.fromDate = fromDate;
    }
    public String getToDate() {
        return this.toDate;
    }
    
    public void setToDate(String toDate) {
        this.toDate = toDate;
    }
    public String getAchiement() {
        return this.achiement;
    }
    
    public void setAchiement(String achiement) {
        this.achiement = achiement;
    }




}


