package client.entity;
// Generated May 14, 2013 3:06:40 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

/**
 * FeedbackSystem generated by hbm2java
 */
public class FeedbackSystem  implements java.io.Serializable {


     private int id;
     private Customer customer;
     private Worker worker;
     private String infoFeedback;
     private Integer rate;

    public FeedbackSystem() {
    }

	
    public FeedbackSystem(int id) {
        this.id = id;
    }
    public FeedbackSystem(int id, Customer customer, Worker worker, String infoFeedback, Integer rate) {
       this.id = id;
       this.customer = customer;
       this.worker = worker;
       this.infoFeedback = infoFeedback;
       this.rate = rate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Worker getWorker() {
        return this.worker;
    }
    
    public void setWorker(Worker worker) {
        this.worker = worker;
    }
    public String getInfoFeedback() {
        return this.infoFeedback;
    }
    
    public void setInfoFeedback(String infoFeedback) {
        this.infoFeedback = infoFeedback;
    }
    public Integer getRate() {
        return this.rate;
    }
    
    public void setRate(Integer rate) {
        this.rate = rate;
    }




}


