package client.entity;
// Generated May 14, 2013 3:06:40 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Worker generated by hbm2java
 */
public class Worker  implements java.io.Serializable {


     private int id;
     private Account account;
     private String name;
     private Integer age;
     private Boolean gender;
     private String phone;
     private String address;
     private String email;
     private Boolean status;
     private Set<FeedbackSystem> feedbackSystems = new HashSet<FeedbackSystem>(0);
     private Set<Cv> cvs = new HashSet<Cv>(0);
     private Set<Appointment> appointments = new HashSet<Appointment>(0);
     private Set<RecruitmentToWorker> recruitmentToWorkers = new HashSet<RecruitmentToWorker>(0);

    public Worker() {
    }

	
    public Worker(int id) {
        this.id = id;
    }
    public Worker(int id, Account account, String name, Integer age, Boolean gender, String phone, String address, String email, Boolean status, Set<FeedbackSystem> feedbackSystems, Set<Cv> cvs, Set<Appointment> appointments, Set<RecruitmentToWorker> recruitmentToWorkers) {
       this.id = id;
       this.account = account;
       this.name = name;
       this.age = age;
       this.gender = gender;
       this.phone = phone;
       this.address = address;
       this.email = email;
       this.status = status;
       this.feedbackSystems = feedbackSystems;
       this.cvs = cvs;
       this.appointments = appointments;
       this.recruitmentToWorkers = recruitmentToWorkers;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public Boolean getGender() {
        return this.gender;
    }
    
    public void setGender(Boolean gender) {
        this.gender = gender;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set<FeedbackSystem> getFeedbackSystems() {
        return this.feedbackSystems;
    }
    
    public void setFeedbackSystems(Set<FeedbackSystem> feedbackSystems) {
        this.feedbackSystems = feedbackSystems;
    }
    public Set<Cv> getCvs() {
        return this.cvs;
    }
    
    public void setCvs(Set<Cv> cvs) {
        this.cvs = cvs;
    }
    public Set<Appointment> getAppointments() {
        return this.appointments;
    }
    
    public void setAppointments(Set<Appointment> appointments) {
        this.appointments = appointments;
    }
    public Set<RecruitmentToWorker> getRecruitmentToWorkers() {
        return this.recruitmentToWorkers;
    }
    
    public void setRecruitmentToWorkers(Set<RecruitmentToWorker> recruitmentToWorkers) {
        this.recruitmentToWorkers = recruitmentToWorkers;
    }




}


